#!/usr/bin/Rscript
# Copyright (C) 2012 Joel Granados <joel.granados@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# calculate argument list.
cmdArgs = commandArgs()
cmdStr = paste(commandArgs(TRUE), collapse=" ")
cmdCmd = sub("--file=", "", cmdArgs[grep("--file=", cmdArgs)])
cmdDir = dirname(cmdCmd)

# Bring all relevant code into the namespace
source(file.path(cmdDir,"ecoip_plot.R"), chdir=TRUE)

# execute command
retval = ecoip_plot_exec ( arguments=cmdStr )

# exit
q(sa="no", st=retval)
