#!/usr/bin/Rscript
# Copyright (C) 2012 Joel Granados <joel.granados@gmail.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# Files where signals are.
cmdArgs = commandArgs(TRUE)

finalList = list()
elemnumber = list()
for ( i in 1:length(cmdArgs) )
{
    if ( length(cmdArgs) < 1 )
        stop("Did not recieve any arguments")
    if ( !file.exists(cmdArgs[i] ) )
    {
        message( "Ignoring ", cmdArgs[i], ". File does not exists." )
        next
    }

    print ( cmdArgs[i] )

    table = try(read.table(cmdArgs[i]), silent=TRUE)
    if ( class(table) == "try-error" )
    {
        message( "Could not read table in ", cmdArgs[i] )
        next
    }

    table = as.matrix(table)
    table[,1] = substr(basename(table[,1]), 1, 10)

    for ( j in 1:length(table[,1]) )
    {
        if ( is.null(finalList[[table[j,1]]]) )
        {
            finalList[[table[j,1]]] = 0
            elemnumber[[table[j,1]]] = 1
        } else
            elemnumber[[table[j,1]]] = elemnumber[[table[j,1]]] + 1

        finalList[[table[j,1]]] = finalList[[table[j,1]]]+as.numeric(table[j,2])
    }
}

if (TRUE)
    for ( i in 1:length(finalList) )
        finalList[names(finalList)[i]] = ( as.double(finalList[names(finalList)[i]])
                                           / as.double(elemnumber[names(finalList)[i]]) )

# Sort final list
finalList = finalList[order(as.Date(names(finalList)))]

write.table(as.matrix(finalList), file="union.txt", col.names=F, quote=F)
